name: Biya Chain Docs Generation

on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    env: 
      GH_CORE_USER: ${{ secrets.GH_CORE_USER }}
      GH_CORE_TOKEN: ${{ secrets.GH_CORE_TOKEN }}
      GH_DOCS_TOKEN: ${{ secrets.GH_DOCS_TOKEN }}
    steps:
      - name: Checkout biyachain-docs
        uses: actions/checkout@v1
        with:
          repository: biya-coin/biyachain-docs
          ref: dev
          path: ./biyachain-docs

      - name: Generate new docs from biyachain-core
        run: |
          export GH_CORE_USER=${{ secrets.GH_CORE_USER }}
          export GH_CORE_TOKEN=${{ secrets.GH_CORE_TOKEN }}
          export GH_DOCS_TOKEN=${{ secrets.GH_DOCS_TOKEN }}
          ./scripts/setup.sh

      - name: Set up Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Commit the changes to biyachain-docs
        run: |
          git add .
          git commit -m "chore: docs regenerated" || echo "No changes to commit"
          git remote set-url origin https://${{ secrets.GH_CORE_USER }}:${{ secrets.GH_DOCS_TOKEN }}@github.com/biya-coin/biyachain-docs.git
          git push || echo "No changes to push"
